package main

import (
	"fmt"
	"log"
	"os"

	"github.com/gohryt/asphyxia/bytes"
)

const (
	ToLower = 'a' - 'A'

	description = `// Code generated by go run generate/table.go; DO NOT EDIT.
// See generate/table.go for more information about these tables.

package percent

`
)

func main() {
	hex2intTable := [256]byte{}

	for i := 0; i < 256; i++ {
		c := byte(16)
		if i >= '0' && i <= '9' {
			c = byte(i) - '0'
		} else if i >= 'a' && i <= 'f' {
			c = byte(i) - 'a' + 10
		} else if i >= 'A' && i <= 'F' {
			c = byte(i) - 'A' + 10
		}
		hex2intTable[i] = c
	}

	toLowerTable := [256]byte{}

	for i := 0; i < 256; i++ {
		c := byte(i)
		if c >= 'A' && c <= 'Z' {
			c += ToLower
		}
		toLowerTable[i] = c
	}

	toUpperTable := [256]byte{}

	for i := 0; i < 256; i++ {
		c := byte(i)
		if c >= 'a' && c <= 'z' {
			c -= ToLower
		}
		toUpperTable[i] = c
	}

	quotedArgumentShouldEscapeTable := [256]byte{}

	for i := 0; i < 256; i++ {
		quotedArgumentShouldEscapeTable[i] = 1
	}

	// ALPHA
	for i := int('a'); i <= int('z'); i++ {
		quotedArgumentShouldEscapeTable[i] = 0
	}
	for i := int('A'); i <= int('Z'); i++ {
		quotedArgumentShouldEscapeTable[i] = 0
	}

	// DIGIT
	for i := int('0'); i <= int('9'); i++ {
		quotedArgumentShouldEscapeTable[i] = 0
	}

	// Unreserved characters
	for _, v := range `-_.~` {
		quotedArgumentShouldEscapeTable[v] = 0
	}

	quotedPathShouldEscapeTable := quotedArgumentShouldEscapeTable

	for _, v := range `$&+,/:;=@` {
		quotedPathShouldEscapeTable[v] = 0
	}

	buffer := bytes.Buffer(description)

	fmt.Fprintf(&buffer, "const hex2intTable = %q\n", hex2intTable)
	fmt.Fprintf(&buffer, "const toLowerTable = %q\n", toLowerTable)
	fmt.Fprintf(&buffer, "const toUpperTable = %q\n", toUpperTable)
	fmt.Fprintf(&buffer, "const quotedArgShouldEscapeTable = %q\n", quotedArgumentShouldEscapeTable)
	fmt.Fprintf(&buffer, "const quotedPathShouldEscapeTable = %q\n", quotedPathShouldEscapeTable)

	err := os.WriteFile("table.go", buffer, 0o660)
	if err != nil {
		log.Fatal(err)
	}
}
